package cc.kertaskerja.tppkepegawaian.jabatan.domain;

public enum JenisJabatan {
    JABATAN_PEMIMPIN_TINGGI_PRATAMA,
	JABATAN_PEMIMPIN_TINGGI,
	JABATAN_STRUKTURAL,
	JABATAN_FUNGSIONAL,
	JABATAN_ADMINISTRASI,
    JABATAN_ADMINISTRATOR,
    JABATAN_PENGAWAS,
	PELAKSANA,
	BELUM_DIATUR;
}
