server:
  port: 8001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: tpp-kepegawaian
  cache:
    type: redis
  data:
    redis:
      host: 192.168.194.241
      port: 6379
      timeout: 60000
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://192.168.194.241:5432/kertaskerja_kepegawaian
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

kertaskerja:
  status: TPP Kepegawaian UP!

management:
  endpoints:
    web:
      exposure:
        include: mappings