ALTER TABLE jabatan
ALTER COLUMN status_jabatan TYPE VARCHAR(255),
ALTER COLUMN jenis_jabatan TYPE VARCHAR(255),
ALTER COLUMN eselon TYPE VARCHAR(255),
ALTER COLUMN pangkat TYPE VARCHAR(255),
ALTER COLUMN golongan TYPE VARCHAR(255);
